export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const LOAD_MESSAGE = 'LOAD_MESSAGE';
export const LOAD_USERS = 'LOAD_USERS';
export const USERS_FETCHED = 'USERS_FETCHED';
export const LOAD_CHAT_HISTORY = 'LOAD_CHAT_HISTORY';